version: "3"
services:
  web-1:
    container_name: changui
    build: .
    volumes:
      - "volumes-container:/usr/share/nginx/html"
    ports:
      - "91:80"
    restart: always
volumes:
  volumes-container:
